version: '3.9'

services:
  selenium:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: selenium_scrapper_agent_manager_on_web
    restart: always
    volumes:
      - .:/app
      - ./telechargements:/app/telechargements  
    working_dir: /app
    command: python automate.py
